name: "NVS Scanner for GitHub Action"
on:
  push:
    branches:
      - master
      - 'releases/*'
      - 'intc-*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with:
        email: your_email@something.com
        password: ${{ secrets.NVS_SCANNER_PASSWORD }}
        directory: lib
